name: frog 
base: core22 
grade: stable 
confinement: strict 
adopt-info: frog
compression: lzo
source-code: https://github.com/TenderOwl/Frog
website: https://getfrog.app
issues: https://github.com/soumyaDghosh/frog-snap/issues/new/choose
license: MIT

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

parts:
  pytesseract:
    source: .
# ext:updatesnap
#   version-format:
#     ignore: true
    plugin: python
    build-environment:
      - PATH: ${CRAFT_PART_INSTALL}/bin:${PATH}
      - PYTHONPATH: ""
    python-packages:
      - pytesseract==0.3.10
      - pyzbar==0.1.9
      - gTTS==2.4.0
      - python-dateutil==2.8.2
      - loguru==0.7.2
      - nanoid==2.0.0
      - posthog==3.4.0
    prime:
      - -usr/bin/activate*
      - -usr/bin/Activate.ps1
      - -usr/bin/python*
      - -usr/bin/pip*
      - -usr/lib/*/*/pip*
      - -usr/lib/*/*/pkg_resources
      - -usr/lib/*/*/setuptools*
      - -usr/lib/*/*/_dist*
      - -pyvenv.cfg
      - -lib
      - -lib64
      - -include
    organize:
      bin: usr/bin
      lib/python3.10/site-packages: usr/lib/python3/dist-packages
  frog:
    plugin: meson
    source: https://github.com/TenderOwl/Frog.git
    source-tag: '1.5.1'
    source-depth: 1
    meson-parameters:
      - --prefix=/snap/frog/current/usr
    build-packages:
      - libleptonica-dev
      - tesseract-ocr
    build-snaps:
      - blueprint-compiler
    build-environment:
      - GI_TYPELIB_PATH: /snap/gnome-42-2204-sdk/current/usr/lib/girepository-1.0:/snap/gnome-42-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0
    override-pull: |
      craftctl default
      sed -e "s|install_subdir('frog', install_dir: pythondir)|install_subdir('frog', install_dir: '/snap/frog/current/usr/lib/python3/dist-packages')|g" -i meson.build
      sed -i 's#/app#\/snap/frog/current/usr#' $CRAFT_PART_SRC/frog/language_manager.py
    override-build: |
      craftctl default
      # WORKAROUND: Use python from search path, the path detected by meson doesn't exist when running the Snap
      sed -e '1c#!/usr/bin/env python3' -i "${CRAFT_PART_INSTALL}/snap/frog/current/usr/bin/frog"
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp -r $CRAFT_PART_INSTALL/snap/frog/current/usr/share/icons $CRAFT_PART_INSTALL/meta/gui/
      for i in `find $CRAFT_PART_INSTALL/meta/gui/icons -name "*.svg" -o -name "*.png"`; do
        mv $i "`dirname $i`/snap.$CRAFT_PROJECT_NAME.`basename $i`"
      done
    parse-info: [usr/share/appdata/com.github.tenderowl.frog.appdata.xml]
    organize:
      snap/frog/current: .
  deps:
    plugin: nil
    stage-packages:
      - tesseract-ocr
      - liblept5
      - libgif7
      - libzbar0
      - gir1.2-gstreamer-1.0
    prime:
      - usr/bin/tesseract
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libtesseract.so.4
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libtesseract.so.4.0.1
      - usr/lib/*/libzbar.so*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/liblept.so.5
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/liblept.so.5.0.4
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgif.so.7
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgif.so.7.1.0
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0/Gst-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0/GstBase-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0/GstCheck-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0/GstController-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0/GstNet-1.0.typelib

slots:
  frog:
    interface: dbus
    bus: session
    name: com.github.tenderowl.frog
apps:
  frog:
    command: usr/bin/frog
    common-id: com.github.tenderowl.frog
    extensions: [gnome]
    desktop: usr/share/applications/com.github.tenderowl.frog.desktop
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
      #DYLD_LIBRARY_PATH: $LD_LIBRARY_PATH
    plugs:
      - network
      - network-status
      - audio-playback
