name: frog # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.2.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
compression: lzo
#environment:
  # WORKAROUND: Add python modules in Snap to search path
 # PYTHONPATH: ${SNAP}/lib/python3.10/site-packages:${SNAP}/usr/lib/python3/dist-packages
layout:
  /usr/share/frog:
    bind: $SNAP/usr/share/frog
  /usr/local/lib/python3.10/dist-packages/frog:
    bind: $SNAP/usr/local/lib/python3.10/dist-packages/frog
  /usr/lib/python3/dist-packages:
    bind: $SNAP/usr/lib/python3/dist-packages
parts:
  meson:
    plugin: python
    source: https://github.com/mesonbuild/meson.git
    source-tag: 1.0.0
    build-environment:
      # WORKAROUND: The python plugin is broken with gnome extension
      - PATH: ${CRAFT_PART_INSTALL}/bin:${PATH}
      - PYTHONPATH: ""
    stage:
      # WORKAROUND: Skip venv from python plugin
      - -bin/activate
      - -bin/activate.csh
      - -bin/activate.fish
      - -bin/Activate.ps1
      - -bin/python
      - -bin/python3
      - -bin/python3.10
      - -bin/pip
      - -bin/pip3
      - -bin/pip3.10
      - -pyvenv.cfg
    python-packages:
      - pytesseract
  frog:
    plugin: meson
    source: https://github.com/TenderOwl/Frog.git
    source-type: git
    source-tag: "1.2.0"
    # See 'snapcraft plugins'
    build-packages:
      - ninja-build
      - gettext
      - pkg-config
      - glibc-source
      - libglib2.0-dev
      - desktop-file-utils
      - appstream
      - libappstream-dev 
      - libglib2.0-bin
      - libappstream-glib-dev
      - python-is-python3
      - python3-gi
      - python-gi-dev 
      - python3-pyzbar
      - python3-pydbus 
      - tesseract-ocr 
      - libnotify-dev
      - libleptonica-dev
      - libgtk-3-dev
    stage-packages:
      - gettext
      - pkg-config
      - glibc-source
      - libglib2.0-0
      - libglib2.0-dev
      - desktop-file-utils
      - appstream
      - libappstream-dev 
      - libglib2.0-bin
      - libappstream-glib-dev
      - python-is-python3
      - python3-gi
      - python-gi-dev 
      - python3-pyzbar
      - python3-pydbus 
      - python3-tesserocr 
      - tesseract-ocr 
      - libnotify-dev
      - libleptonica-dev
      - libgtk-3-dev
      - libgtk-4-1
      - python3-pil
    override-pull: |
      craftctl default
      # WORKAROUND: Point icon directly to SVG otherwise snapcraft can't find it
      sed -e 's|Icon=com.github.tenderowl.frog|Icon=/usr/share/icons/hicolor/scalable/apps/com.github.tenderowl.frog.svg|' -i data/com.github.tenderowl.frog.desktop.in
    override-build: |
      craftctl default
      # WORKAROUND: Use python from search path, the path detected by meson doesn't exist when running the Snap
      # sed -e '1c#!/usr/bin/env python3' -i "${CRAFT_PART_INSTALL}/usr/bin/frog"
    parse-info: [/usr/share/appdata/com.github.tenderowl.frog.appdata.xml]
    organize:
      snap/frog/current/usr: usr
slots:
  frog:
    interface: dbus
    bus: session
    name: com.github.tenderowl.frog
plugs:
  pictures:
    interface: personal-files
    write:
      - $HOME/Pictures
apps:
  frog:
    command: usr/bin/frog
    common-id: com.github.tenderowl.frog
    extensions: [gnome]
   # desktop: usr/share/applications/com.github.tenderowl.frog.desktop
    environment:
      PYTHONPATH: ${SNAP}/lib/python3.10/site-packages:${SNAP}/usr/lib/python3/dist-packages
      XDG_DATA_HOME: $SNAP_USER_DATA/.local/share 
    plugs:
      - home
      - pictures
      - network

      
