name: frog # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.3.0' # just for humans, typically '1.2+git' or '1.3.2'
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
adopt-info: frog
icon: com.github.tenderowl.frog.svg
compression: lzo
environment:
   #WORKAROUND: Add python modules in Snap to search path
   PYTHONPATH: ${SNAP}/lib/python3.10/site-packages:${SNAP}/usr/lib/python3/dist-packages
parts:
  #pytesseract:
  #  plugin: python
  #  source: https://github.com/madmaze/pytesseract.git
  #  source-tag: v0.3.10
  #  build-environment:
  #    # WORKAROUND: The python plugin is broken with gnome extension
  #    - PATH: ${CRAFT_PART_INSTALL}/bin:${PATH}
  #    - PYTHONPATH: ""
  #  stage:
  #    # WORKAROUND: Skip venv from python plugin
  #    - -bin/activate
  #    - -bin/activate.csh
  #    - -bin/activate.fish
  #    - -bin/Activate.ps1
  #    - -bin/python
  #    - -bin/python3
  #    - -bin/python3.10
  #    - -bin/pip
  #    - -bin/pip3
  #    - -bin/pip3.10
  #    - -pyvenv.cfg
  #  python-packages:
  #    - pyzbar
  #    - PyGObject
  frog:
    #after: [pytesseract]
    plugin: meson
    source: https://github.com/TenderOwl/Frog.git
    source-type: git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    meson-parameters:
      - --prefix=usr/
    # See 'snapcraft plugins'
    build-environment:
      - PYTHONDIR: /usr/lib/python3.10/dist-packages/
    build-packages:
      - libleptonica-dev
      - libportal-gtk3-dev
      - tesseract-ocr
    stage-packages:
      - tesseract-ocr
    override-build: |
      craftctl default
      pip install --target=$CRAFT_PART_INSTALL/snap/frog/current/usr/lib/python3/dist-packages pytesseract
      # WORKAROUND: Use python from search path, the path detected by meson doesn't exist when running the Snap
      sed -e '1c#!/usr/bin/env python3' -i "${CRAFT_PART_INSTALL}/snap/frog/current/usr/bin/frog"
    parse-info: [usr/share/appdata/com.github.tenderowl.frog.appdata.xml]
    organize:
      snap/frog/current/usr: usr

apps:
  frog:
    command: usr/bin/frog
    common-id: com.github.tenderowl.frog
    extensions: [gnome]
    desktop: usr/share/applications/com.github.tenderowl.frog.desktop
    plugs:
      - network

