name: frog # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
adopt-info: frog
#icon: com.github.tenderowl.frog.svg
compression: lzo
environment:
   #WORKAROUND: Add python modules in Snap to search path
   PYTHONPATH: ${SNAP}/lib/python3.10/site-packages:${SNAP}/usr/lib/python3/dist-packages
parts:
  pytesseract:
    source: https://github.com/madmaze/pytesseract.git
    source-tag: 'v0.3.10'
    plugin: python
    build-environment:
      # WORKAROUND: The python plugin is broken with gnome extension
      - PATH: ${CRAFT_PART_INSTALL}/bin:${PATH}
      - PYTHONPATH: ""
    python-packages:
      - pyzbar==0.1.9
    prime:
      - -usr/bin/activate*
      - -usr/bin/Activate.ps1
      - -usr/bin/python*
      - -usr/bin/pip*
      - -pyvenv.cfg
      - -lib
      - -lib64
      - -include
    organize:
      bin: usr/bin
      lib/python3.10/site-packages: usr/lib/python3/dist-packages
  frog:
    plugin: meson
    source: https://github.com/TenderOwl/Frog.git
    source-tag: '1.3.0'
    meson-parameters:
      - --prefix=/snap/frog/current/usr
    # See 'snapcraft plugins'
    build-packages:
      - libleptonica-dev
      - tesseract-ocr
    build-environment:
      - GI_TYPELIB_PATH: /snap/gnome-42-2204-sdk/current/usr/lib/girepository-1.0:/snap/gnome-42-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0
    override-pull: |
      craftctl default
      sed -e "s|install_subdir('frog', install_dir: pythondir)|install_subdir('frog', install_dir: '/snap/frog/current/usr/lib/python3/dist-packages')|g" -i meson.build
      patch -p1 < $CRAFT_PROJECT_DIR/frog.patch
    override-build: |
      craftctl default
      # WORKAROUND: Use python from search path, the path detected by meson doesn't exist when running the Snap
      sed -e '1c#!/usr/bin/env python3' -i "${CRAFT_PART_INSTALL}/snap/frog/current/usr/bin/frog"
    parse-info: [usr/share/appdata/com.github.tenderowl.frog.appdata.xml]
    organize:
      snap/frog/current: .
  deps:
    plugin: nil
    stage-packages:
      - tesseract-ocr
      - liblept5
      - libzbar0
      - libgif7
    prime:
      - usr/bin/tesseract
      #- usr/bin/text2image
      #- usr/bin/unicharset_extractor
      - usr/lib/$CRAFT_ARCH_TRIPLET/libtesseract.so.4
      - usr/lib/$CRAFT_ARCH_TRIPLET/libtesseract.so.4.0.1
      - usr/lib/$CRAFT_ARCH_TRIPLET/libzbar.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libzbar.so.0.3.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/liblept.so.5
      - usr/lib/$CRAFT_ARCH_TRIPLET/liblept.so.5.0.4
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgif.so.7
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgif.so.7.1.0

slots:
  frog:
    interface: dbus
    bus: session
    name: com.github.tenderowl.frog
apps:
  frog:
    command: usr/bin/frog
    common-id: com.github.tenderowl.frog
    extensions: [gnome]
    desktop: usr/share/applications/com.github.tenderowl.frog.desktop
    environment:
      XDG_DATA_HOME: $SNAP_USER_DATA/.local/share
    plugs:
      - network
